using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Emit;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using Bendric.Api;

namespace Bendric
{
    public class ScriptCompiler
    {
        private string _scriptPath;
        private string _workingDirectory;

        public ScriptCompiler(string scriptPath)
        {
            _scriptPath = scriptPath;
            _workingDirectory = Path.GetDirectoryName(Path.GetFullPath(scriptPath));
        }

        public Assembly Compile()
        {
            Logger.Info("Compiling build script...");

            var scriptContent = File.ReadAllText(_scriptPath);
            scriptContent = $@"
// This code was generated by Bendric at {DateTime.Now.ToString("G")}

using Bendric.Api;
namespace BuildScript {{
class Program {{
{scriptContent}
}}}}";

            // Parse the script
            var syntaxTree = CSharpSyntaxTree.ParseText(scriptContent);

            // Get references
            var references = GetMetadataReferences();

            // Compile
            var compilation = CSharpCompilation.Create(
                assemblyName: Path.GetRandomFileName(),
                syntaxTrees: new[] { syntaxTree },
                references: references,
                options: new CSharpCompilationOptions(
                    OutputKind.DynamicallyLinkedLibrary,
                    optimizationLevel: OptimizationLevel.Release));

            // Emit to memory
            using (var ms = new MemoryStream())
            {
                EmitResult result = compilation.Emit(ms);

                if (!result.Success)
                {
                    Logger.Error("Script compilation failed:");
                    foreach (Diagnostic diagnostic in result.Diagnostics)
                    {
                        if (diagnostic.Severity == DiagnosticSeverity.Error)
                        {
                            Logger.Error($"  {diagnostic.GetMessage()}");
                        }
                        else if (diagnostic.Severity == DiagnosticSeverity.Warning)
                        {
                            Logger.Warn($"  {diagnostic.GetMessage()}");
                        }
                    }
                    return null;
                }

                ms.Seek(0, SeekOrigin.Begin);
                Assembly assembly = Assembly.Load(ms.ToArray());

                Logger.Info("Script compiled successfully");
                return assembly;
            }
        }

        private List<MetadataReference> GetMetadataReferences()
        {
            var references = new List<MetadataReference>();

            // System.dll
            references.Add(MetadataReference.CreateFromFile(typeof(object).Assembly.Location));

            // Bendric.Api.dll
            string bendricApiPath = typeof(Project).Assembly.Location;
            references.Add(MetadataReference.CreateFromFile(bendricApiPath));

            // Additional required assemblies
            references.Add(MetadataReference.CreateFromFile(typeof(Console).Assembly.Location));
            references.Add(MetadataReference.CreateFromFile(typeof(List<>).Assembly.Location));
            references.Add(MetadataReference.CreateFromFile(typeof(Enumerable).Assembly.Location));
            references.Add(MetadataReference.CreateFromFile(typeof(File).Assembly.Location));
            references.Add(MetadataReference.CreateFromFile(typeof(Directory).Assembly.Location));

            // System.Runtime
            string systemRuntimePath = Path.Combine(
                Path.GetDirectoryName(typeof(object).Assembly.Location),
                "System.Runtime.dll");
            if (File.Exists(systemRuntimePath))
            {
                references.Add(MetadataReference.CreateFromFile(systemRuntimePath));
            }

            // System.Collections
            string systemCollectionsPath = Path.Combine(
                Path.GetDirectoryName(typeof(object).Assembly.Location),
                "System.Collections.dll");
            if (File.Exists(systemCollectionsPath))
            {
                references.Add(MetadataReference.CreateFromFile(systemCollectionsPath));
            }

            // System.Linq
            string systemLinqPath = Path.Combine(
                Path.GetDirectoryName(typeof(object).Assembly.Location),
                "System.Linq.dll");
            if (File.Exists(systemLinqPath))
            {
                references.Add(MetadataReference.CreateFromFile(systemLinqPath));
            }

            // System.IO.FileSystem
            string systemIOPath = Path.Combine(
                Path.GetDirectoryName(typeof(object).Assembly.Location),
                "System.IO.FileSystem.dll");
            if (File.Exists(systemIOPath))
            {
                references.Add(MetadataReference.CreateFromFile(systemIOPath));
            }

            return references;
        }
    }
}
